name: Deploy Prod

on:
    workflow_dispatch:

jobs:
    deploy-dev:
        name: Deploy To Dev
        runs-on: ubuntu-latest
        environment: prod
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Deploy to Vercel Preview
              run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
              env:
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
